name: Production Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch

jobs:
  test-and-deploy-to-netlify:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install Netlify CLI
        run: yarn global add netlify-cli
        
      - name: Install dependencies
        run: yarn install

      # Run tests
      - name: Run tests
        run: yarn test

      # Build the application
      - name: Build application
        run: yarn build

      # Deploy to Netlify
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: './dist'  # Directory where Vite build outputs
