name: Production Workflow

on:
  push:
    branch:
      -main
jobs:
  # Name of the job
  test-and-deploy-to-netlify:
    # Operating system to run on
    runs-on: ubuntu-latest

    # List of steps that make up the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    # Install dependencies
    - name: Install Netlify
      run: yarn add netlify-cli
      
    - name: Install dependencies
      run: yarn install

    # Run tests
    - name: Run tests
<<<<<<< HEAD
      run: yarn test  
=======
      run: yarn run test
>>>>>>> fd40115be91c57e9690f1377e3ae4119ecfc4db5

    # Deploy to Netlify
    - name: Netlify Deploy
      uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        # Auth token to use with netlify
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        # Your Netlify site id
        NETLIFY_SITE_ID:  ${{ secrets.NETLIFY_SITE_ID }}
        # Directory where built files are stored
        build_directory: './dist'
        # Command to install dependencies
        install_command: yarn install
        # Command to build static website
        build_command: yarn build
